version: 2.1
jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - jq/install
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Make html
          command: cd docs && make html
      - run:
          name: Link check
          command: cd docs && make linkcheck
      - run:
          name: Discourse Topic Check
          command: |
            if [ -n $CIRCLE_PULL_REQUEST ]; then
              bash discourse-topic-check.sh
            else
              echo "This check was not done as it was not a PR"
            fi
orbs:
  jq: circleci/jq@2.2.0
workflows:
  version: 2.1
  build:
    jobs:
      - test
