version: 2 
jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - install/jq
#      - run:
#          name: Install dependencies
#          command: pip install -r requirements.txt
#      - run:
#          name: Make html
#          command: cd docs && make html
#      - run:
#          name: Link check
#          command: cd docs && make linkcheck
      - run:
          name: Discourse Topic Check
          command: bash discourse-topic-check.sh
orbs:
  jq: circleci/jq@2.2.0
workflows:
  version: 2
  build:
    jobs:
      - test
